// Demo Work Orders yang sudah Completed untuk Kartu Kendali
import { WorkOrder, Ticket } from '../types';

export const getCompletedWorkOrdersDemo = (): WorkOrder[] => {
  const now = new Date();
  const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);
  const fiveDaysAgo = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000);
  const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const eightDaysAgo = new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000);
  const tenDaysAgo = new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000);
  const twelveDaysAgo = new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000);
  const fifteenDaysAgo = new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000);

  return [
    // ========== TICKET 1: Laptop Dell Latitude E5470 - 3 Work Orders ==========
    {
      id: 'wo-comp-001',
      ticketId: 'ticket-comp-001',
      ticketNumber: 'TKT-PR-20251103-1234',
      type: 'sparepart',
      status: 'completed',
      itemName: 'Casing Laptop',
      quantity: 1,
      createdBy: 'user-4',
      createdAt: weekAgo.toISOString(),
      updatedAt: threeDaysAgo.toISOString(),
      completedAt: threeDaysAgo.toISOString(),
      timeline: [
        {
          id: 'woc1-tl-1',
          timestamp: weekAgo.toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Andi Wijaya',
          details: 'Work Order sparepart dibuat untuk casing laptop yang retak',
        },
        {
          id: 'woc1-tl-2',
          timestamp: fiveDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement casing laptop dimulai',
        },
        {
          id: 'woc1-tl-3',
          timestamp: threeDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'Casing telah diterima dan dipasang',
        },
      ],
    },
    {
      id: 'wo-comp-002',
      ticketId: 'ticket-comp-001',
      ticketNumber: 'TKT-PR-20251103-1234',
      type: 'sparepart',
      status: 'completed',
      itemName: 'Baterai Laptop',
      quantity: 1,
      createdBy: 'user-4',
      createdAt: weekAgo.toISOString(),
      updatedAt: threeDaysAgo.toISOString(),
      completedAt: threeDaysAgo.toISOString(),
      timeline: [
        {
          id: 'woc2-tl-1',
          timestamp: weekAgo.toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Andi Wijaya',
          details: 'Work Order sparepart dibuat untuk baterai yang drop',
        },
        {
          id: 'woc2-tl-2',
          timestamp: fiveDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement baterai original dimulai',
        },
        {
          id: 'woc2-tl-3',
          timestamp: threeDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'Baterai telah diterima dan dipasang',
        },
      ],
    },
    {
      id: 'wo-comp-003',
      ticketId: 'ticket-comp-001',
      ticketNumber: 'TKT-PR-20251103-1234',
      type: 'sparepart',
      status: 'completed',
      itemName: 'Keyboard Laptop',
      quantity: 1,
      createdBy: 'user-4',
      createdAt: weekAgo.toISOString(),
      updatedAt: threeDaysAgo.toISOString(),
      completedAt: threeDaysAgo.toISOString(),
      timeline: [
        {
          id: 'woc3-tl-1',
          timestamp: weekAgo.toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Andi Wijaya',
          details: 'Work Order sparepart dibuat untuk keyboard yang tidak berfungsi',
        },
        {
          id: 'woc3-tl-2',
          timestamp: fiveDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement keyboard backlit dimulai',
        },
        {
          id: 'woc3-tl-3',
          timestamp: threeDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'Keyboard telah diterima dan dipasang',
        },
      ],
    },

    // ========== TICKET 2: Printer HP LaserJet P1102 - 2 Work Orders ==========
    {
      id: 'wo-comp-004',
      ticketId: 'ticket-comp-002',
      ticketNumber: 'TKT-PR-20251028-5678',
      type: 'sparepart',
      status: 'completed',
      itemName: 'Toner HP CE285A',
      quantity: 2,
      createdBy: 'user-5',
      createdAt: twelveDaysAgo.toISOString(),
      updatedAt: eightDaysAgo.toISOString(),
      completedAt: eightDaysAgo.toISOString(),
      timeline: [
        {
          id: 'woc4-tl-1',
          timestamp: twelveDaysAgo.toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Rudi Hartono',
          details: 'Work Order sparepart dibuat untuk toner printer',
        },
        {
          id: 'woc4-tl-2',
          timestamp: tenDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement toner HP dimulai',
        },
        {
          id: 'woc4-tl-3',
          timestamp: eightDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'Toner telah diterima dan dipasang',
        },
      ],
    },
    {
      id: 'wo-comp-005',
      ticketId: 'ticket-comp-002',
      ticketNumber: 'TKT-PR-20251028-5678',
      type: 'vendor',
      status: 'completed',
      createdBy: 'user-5',
      createdAt: twelveDaysAgo.toISOString(),
      updatedAt: eightDaysAgo.toISOString(),
      completedAt: eightDaysAgo.toISOString(),
      vendorInfo: {
        name: 'PT Service Center HP',
        contact: '08123456789',
        description: 'Cleaning & Service Printer',
      },
      timeline: [
        {
          id: 'woc5-tl-1',
          timestamp: twelveDaysAgo.toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Rudi Hartono',
          details: 'Work Order vendor dibuat untuk service printer',
        },
        {
          id: 'woc5-tl-2',
          timestamp: tenDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Koordinasi dengan vendor service center',
        },
        {
          id: 'woc5-tl-3',
          timestamp: eightDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'Service cleaning printer selesai dilakukan',
        },
      ],
    },

    // ========== TICKET 3: Scanner Canon DR-C225 - 1 Work Order ==========
    {
      id: 'wo-comp-006',
      ticketId: 'ticket-comp-003',
      ticketNumber: 'TKT-PR-20251025-9012',
      type: 'sparepart',
      status: 'completed',
      itemName: 'ADF Roller',
      quantity: 1,
      createdBy: 'user-4',
      createdAt: fifteenDaysAgo.toISOString(),
      updatedAt: tenDaysAgo.toISOString(),
      completedAt: tenDaysAgo.toISOString(),
      timeline: [
        {
          id: 'woc6-tl-1',
          timestamp: fifteenDaysAgo.toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Andi Wijaya',
          details: 'Work Order sparepart dibuat untuk ADF roller yang aus',
        },
        {
          id: 'woc6-tl-2',
          timestamp: twelveDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement ADF roller dimulai',
        },
        {
          id: 'woc6-tl-3',
          timestamp: tenDaysAgo.toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'ADF roller telah diterima dan dipasang',
        },
      ],
    },

    // ========== TICKET 4: Monitor LED Samsung - 2 Work Orders ==========
    {
      id: 'wo-comp-007',
      ticketId: 'ticket-comp-004',
      ticketNumber: 'TKT-PR-20251020-3456',
      type: 'sparepart',
      status: 'completed',
      itemName: 'Power Supply Monitor',
      quantity: 1,
      createdBy: 'user-5',
      createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      completedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      timeline: [
        {
          id: 'woc7-tl-1',
          timestamp: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Rudi Hartono',
          details: 'Work Order sparepart dibuat untuk power supply',
        },
        {
          id: 'woc7-tl-2',
          timestamp: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement power supply dimulai',
        },
        {
          id: 'woc7-tl-3',
          timestamp: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'Power supply telah diterima dan dipasang',
        },
      ],
    },
    {
      id: 'wo-comp-008',
      ticketId: 'ticket-comp-004',
      ticketNumber: 'TKT-PR-20251020-3456',
      type: 'sparepart',
      status: 'completed',
      itemName: 'Kabel VGA',
      quantity: 1,
      createdBy: 'user-5',
      createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      completedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      timeline: [
        {
          id: 'woc8-tl-1',
          timestamp: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Rudi Hartono',
          details: 'Work Order sparepart dibuat untuk kabel VGA',
        },
        {
          id: 'woc8-tl-2',
          timestamp: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement kabel VGA dimulai',
        },
        {
          id: 'woc8-tl-3',
          timestamp: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'Kabel VGA telah diterima',
        },
      ],
    },

    // ========== TICKET 5: Komputer PC Lenovo - 4 Work Orders ==========
    {
      id: 'wo-comp-009',
      ticketId: 'ticket-comp-005',
      ticketNumber: 'TKT-PR-20251015-7890',
      type: 'sparepart',
      status: 'completed',
      itemName: 'RAM DDR4 8GB',
      quantity: 2,
      createdBy: 'user-4',
      createdAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      completedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      timeline: [
        {
          id: 'woc9-tl-1',
          timestamp: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Andi Wijaya',
          details: 'Work Order sparepart dibuat untuk RAM',
        },
        {
          id: 'woc9-tl-2',
          timestamp: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement RAM dimulai',
        },
        {
          id: 'woc9-tl-3',
          timestamp: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'RAM telah diterima dan dipasang',
        },
      ],
    },
    {
      id: 'wo-comp-010',
      ticketId: 'ticket-comp-005',
      ticketNumber: 'TKT-PR-20251015-7890',
      type: 'sparepart',
      status: 'completed',
      itemName: 'SSD 256GB',
      quantity: 1,
      createdBy: 'user-4',
      createdAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      completedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      timeline: [
        {
          id: 'woc10-tl-1',
          timestamp: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Andi Wijaya',
          details: 'Work Order sparepart dibuat untuk SSD',
        },
        {
          id: 'woc10-tl-2',
          timestamp: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement SSD dimulai',
        },
        {
          id: 'woc10-tl-3',
          timestamp: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'SSD telah diterima dan dipasang',
        },
      ],
    },
    {
      id: 'wo-comp-011',
      ticketId: 'ticket-comp-005',
      ticketNumber: 'TKT-PR-20251015-7890',
      type: 'sparepart',
      status: 'completed',
      itemName: 'Power Supply 500W',
      quantity: 1,
      createdBy: 'user-4',
      createdAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      completedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      timeline: [
        {
          id: 'woc11-tl-1',
          timestamp: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Andi Wijaya',
          details: 'Work Order sparepart dibuat untuk power supply',
        },
        {
          id: 'woc11-tl-2',
          timestamp: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement power supply dimulai',
        },
        {
          id: 'woc11-tl-3',
          timestamp: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'Power supply telah diterima dan dipasang',
        },
      ],
    },
    {
      id: 'wo-comp-012',
      ticketId: 'ticket-comp-005',
      ticketNumber: 'TKT-PR-20251015-7890',
      type: 'sparepart',
      status: 'completed',
      itemName: 'Fan Casing',
      quantity: 2,
      createdBy: 'user-4',
      createdAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      completedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      timeline: [
        {
          id: 'woc12-tl-1',
          timestamp: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'WORK_ORDER_CREATED',
          actor: 'Andi Wijaya',
          details: 'Work Order sparepart dibuat untuk fan casing',
        },
        {
          id: 'woc12-tl-2',
          timestamp: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_IN_PROCUREMENT',
          actor: 'Budi Santoso',
          details: 'Procurement fan casing dimulai',
        },
        {
          id: 'woc12-tl-3',
          timestamp: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
          action: 'STATUS_CHANGED_COMPLETED',
          actor: 'Budi Santoso',
          details: 'Fan casing telah diterima dan dipasang',
        },
      ],
    },
  ];
};

export const getCompletedTicketsDemo = (): Ticket[] => {
  const now = new Date();
  const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const twelveDaysAgo = new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000);
  const fifteenDaysAgo = new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000);
  const twentyDaysAgo = new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000);
  const twentyFiveDaysAgo = new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000);

  return [
    // ========== Ticket 1: Laptop Dell Latitude E5470 ==========
    {
      id: 'ticket-comp-001',
      ticketNumber: 'TKT-PR-20251103-1234',
      userId: 'user-6',
      userName: 'Dewi Lestari',
      userEmail: 'user1@bps-ntb.go.id',
      userPhone: '081234567895',
      unitKerja: 'Statistik Produksi',
      title: 'Laptop Rusak Fisik',
      description: 'Laptop rusak casing retak, keyboard tidak berfungsi, baterai drop',
      type: 'perbaikan',
      categoryId: 'cat-2',
      status: 'closed',
      priority: 'P2',
      assetCode: 'LAP-2020-0142',
      assetNUP: '12345678-20200142',
      assetLocation: 'Ruang Statistik Produksi Lt. 2',
      data: {
        itemName: 'Laptop Dell Latitude E5470',
        itemType: 'Laptop',
        brand: 'Dell',
        nupBmn: '12345678-20200142',
        location: 'Ruang Statistik Produksi Lt. 2',
        issueDescription: 'Casing laptop retak, keyboard beberapa tombol tidak berfungsi, baterai cepat habis',
      },
      attachments: [],
      timeline: [
        {
          id: 'tc1-tl-1',
          timestamp: weekAgo.toISOString(),
          action: 'TICKET_CREATED',
          actor: 'Dewi Lestari',
          details: 'Tiket dibuat',
        },
        {
          id: 'tc1-tl-2',
          timestamp: weekAgo.toISOString(),
          action: 'TICKET_ASSIGNED',
          actor: 'Admin Layanan',
          details: 'Tiket ditugaskan ke teknisi Andi Wijaya',
        },
      ],
      assignedTo: 'user-4',
      createdAt: weekAgo.toISOString(),
      updatedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },

    // ========== Ticket 2: Printer HP LaserJet P1102 ==========
    {
      id: 'ticket-comp-002',
      ticketNumber: 'TKT-PR-20251028-5678',
      userId: 'user-7',
      userName: 'Ahmad Fauzi',
      userEmail: 'user2@bps-ntb.go.id',
      userPhone: '081234567896',
      unitKerja: 'IT',
      title: 'Printer Hasil Cetak Buruk',
      description: 'Printer hasil cetak bergaris dan buram',
      type: 'perbaikan',
      categoryId: 'cat-3',
      status: 'closed',
      priority: 'P3',
      assetCode: 'PRT-2019-0089',
      assetNUP: '23456789-20190089',
      assetLocation: 'Ruang IT Lt. 3',
      data: {
        itemName: 'Printer HP LaserJet P1102',
        itemType: 'Printer',
        brand: 'HP',
        nupBmn: '23456789-20190089',
        location: 'Ruang IT Lt. 3',
        issueDescription: 'Hasil cetak bergaris hitam dan buram, toner perlu diganti, perlu service',
      },
      attachments: [],
      timeline: [
        {
          id: 'tc2-tl-1',
          timestamp: twelveDaysAgo.toISOString(),
          action: 'TICKET_CREATED',
          actor: 'Ahmad Fauzi',
          details: 'Tiket dibuat',
        },
        {
          id: 'tc2-tl-2',
          timestamp: twelveDaysAgo.toISOString(),
          action: 'TICKET_ASSIGNED',
          actor: 'Admin Layanan',
          details: 'Tiket ditugaskan ke teknisi Rudi Hartono',
        },
      ],
      assignedTo: 'user-5',
      createdAt: twelveDaysAgo.toISOString(),
      updatedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },

    // ========== Ticket 3: Scanner Canon DR-C225 ==========
    {
      id: 'ticket-comp-003',
      ticketNumber: 'TKT-PR-20251025-9012',
      userId: 'user-8',
      userName: 'Siti Aminah',
      userEmail: 'user3@bps-ntb.go.id',
      userPhone: '081234567897',
      unitKerja: 'Administrasi',
      title: 'Scanner Tidak Bisa Menarik Kertas',
      description: 'Scanner ADF tidak bisa menarik kertas dengan baik, sering paper jam',
      type: 'perbaikan',
      categoryId: 'cat-3',
      status: 'closed',
      priority: 'P2',
      assetCode: 'SCN-2021-0045',
      assetNUP: '34567890-20210045',
      assetLocation: 'Ruang Administrasi Lt. 1',
      data: {
        itemName: 'Scanner Canon DR-C225',
        itemType: 'Scanner',
        brand: 'Canon',
        nupBmn: '34567890-20210045',
        location: 'Ruang Administrasi Lt. 1',
        issueDescription: 'Scanner ADF tidak bisa menarik kertas, roller aus dan perlu diganti',
      },
      attachments: [],
      timeline: [
        {
          id: 'tc3-tl-1',
          timestamp: fifteenDaysAgo.toISOString(),
          action: 'TICKET_CREATED',
          actor: 'Siti Aminah',
          details: 'Tiket dibuat',
        },
        {
          id: 'tc3-tl-2',
          timestamp: fifteenDaysAgo.toISOString(),
          action: 'TICKET_ASSIGNED',
          actor: 'Admin Layanan',
          details: 'Tiket ditugaskan ke teknisi Andi Wijaya',
        },
      ],
      assignedTo: 'user-4',
      createdAt: fifteenDaysAgo.toISOString(),
      updatedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },

    // ========== Ticket 4: Monitor LED Samsung 22 inch ==========
    {
      id: 'ticket-comp-004',
      ticketNumber: 'TKT-PR-20251020-3456',
      userId: 'user-9',
      userName: 'Budi Prasetyo',
      userEmail: 'user4@bps-ntb.go.id',
      userPhone: '081234567898',
      unitKerja: 'Keuangan',
      title: 'Monitor Tidak Menyala',
      description: 'Monitor LED tidak menampilkan gambar, lampu power berkedip',
      type: 'perbaikan',
      categoryId: 'cat-2',
      status: 'closed',
      priority: 'P2',
      assetCode: 'MON-2022-0198',
      assetNUP: '45678901-20220198',
      assetLocation: 'Ruang Keuangan Lt. 2',
      data: {
        itemName: 'Monitor LED Samsung 22 inch',
        itemType: 'Monitor',
        brand: 'Samsung',
        nupBmn: '45678901-20220198',
        location: 'Ruang Keuangan Lt. 2',
        issueDescription: 'Monitor tidak menyala, lampu power berkedip-kedip, power supply rusak',
      },
      attachments: [],
      timeline: [
        {
          id: 'tc4-tl-1',
          timestamp: twentyDaysAgo.toISOString(),
          action: 'TICKET_CREATED',
          actor: 'Budi Prasetyo',
          details: 'Tiket dibuat',
        },
        {
          id: 'tc4-tl-2',
          timestamp: twentyDaysAgo.toISOString(),
          action: 'TICKET_ASSIGNED',
          actor: 'Admin Layanan',
          details: 'Tiket ditugaskan ke teknisi Rudi Hartono',
        },
      ],
      assignedTo: 'user-5',
      createdAt: twentyDaysAgo.toISOString(),
      updatedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    },

    // ========== Ticket 5: Komputer PC Lenovo ThinkCentre ==========
    {
      id: 'ticket-comp-005',
      ticketNumber: 'TKT-PR-20251015-7890',
      userId: 'user-10',
      userName: 'Rina Susanti',
      userEmail: 'user5@bps-ntb.go.id',
      userPhone: '081234567899',
      unitKerja: 'SDM',
      title: 'Komputer Lemot dan Sering Restart',
      description: 'PC sangat lambat, sering restart sendiri, perlu upgrade hardware',
      type: 'perbaikan',
      categoryId: 'cat-2',
      status: 'closed',
      priority: 'P3',
      assetCode: 'PC-2018-0067',
      assetNUP: '56789012-20180067',
      assetLocation: 'Ruang SDM Lt. 1',
      data: {
        itemName: 'Komputer PC Lenovo ThinkCentre M720',
        itemType: 'Komputer',
        brand: 'Lenovo',
        nupBmn: '56789012-20180067',
        location: 'Ruang SDM Lt. 1',
        issueDescription: 'PC sangat lambat, RAM kurang, HDD rusak, power supply bunyi berisik, perlu upgrade',
      },
      attachments: [],
      timeline: [
        {
          id: 'tc5-tl-1',
          timestamp: twentyFiveDaysAgo.toISOString(),
          action: 'TICKET_CREATED',
          actor: 'Rina Susanti',
          details: 'Tiket dibuat',
        },
        {
          id: 'tc5-tl-2',
          timestamp: twentyFiveDaysAgo.toISOString(),
          action: 'TICKET_ASSIGNED',
          actor: 'Admin Layanan',
          details: 'Tiket ditugaskan ke teknisi Andi Wijaya',
        },
      ],
      assignedTo: 'user-4',
      createdAt: twentyFiveDaysAgo.toISOString(),
      updatedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];
};
